### ISSUE TITLE
Snackbars are not possible without icons

### ISSUE THREAD

**Issue by HowDidUGetOutOfBounds** [saimon4u/Compose-Modified-Snackbar#1]
Hi, pal!
I've noticed, that there is no option to pass `null` as icon in case when i don't want to have icon in a snackbar.
I would like to add this functionality and open PR

**Comment by HowDidUGetOutOfBounds** [comment]
@saimon4u, could you please provide permissions to open PR?

**Comment by saimon4u** [comment]
Please open a PR

**Comment by saimon4u** [comment]
Please create a PR

**Comment by HowDidUGetOutOfBounds** [comment]
![image](https://github.com/user-attachments/assets/87072948-c3cf-47c8-8fc2-4640e206bbfc)
Don't have permissions to push a branch, @saimon4u  could you please grant some? =)
